name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      denops_version:
        description: Denops version
        required: false
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get DENOPS_VERSION
        id: vars
        run: |
          if [[ "${{ github.event.inputs.denops_version }}" -ne "" ]]; then
            echo '::set-output name=DENOPS_VERSION=${{ github.event.inputs.denops_version }}'
          else
            echo '::set-output name=DENOPS_VERSION=main'
          fi
        shell: bash
      - run: make DENOPS_VERSION=${{ steps.vars.outputs.DENOPS_VERSION }} build
      - run: make DENOPS_VERSION=${{ steps.vars.outputs.DENOPS_VERSION }} push
