name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      denops_version:
        description: Denops version
        required: false
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get DENOPS_VERSION
        id: vars
        run: |
          if [[ -z "${{ github.event.inputs.denops_version }}" ]]; then
            echo '::set-output name=DENOPS_VERSION::main'
          else
            echo '::set-output name=DENOPS_VERSION::${{ github.event.inputs.denops_version }}'
          fi
        shell: bash
      - run: make DENOPS_VERSION=${{ steps.vars.outputs.DENOPS_VERSION }} build
      - run: make DENOPS_VERSION=${{ steps.vars.outputs.DENOPS_VERSION }} push
